name=ScioSense_UFC23
version=1.0.0
author=ScioSense
maintainer=ScioSense
sentence=Library for the UFC23 ultrasonic flow sensor by ScioSense
paragraph=Enables you to use the UFC23 sensor SPI.
category=Sensors
url=https://github.com/sciosense/ufc23-arduino
architectures=*
